server:
  port: 8060


spring:
  application:
    name: upms
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://106.12.208.53:3306/webuy_upms?useUnicode=true&characterEncoding=UTF-8&allowMutiQueries=true&serverTimezone=Asia/Shanghai
    username: user01
    password: ak402507979
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  cloud:
    consul:
      host: 127.0.0.1
      discovery:
        prefer-ip-address: true
        instance-id: ${spring.application.name}:${spring.cloud.consul.discovery.ip-address}:${server.port}
        ip-address: 127.0.0.1
        health-check-path: /endpoint/_common/_health
        health-check-critical-timeout: 60s
        health-check-interval: 30s

mybatis:
  mapper-locations: classpath*:config/mybatis/mapper/**/*.xml

common:
  db:
    encrypt:
      enable: true
      password-file: classpath:db-encrypt.key